volumes:
  db:
  redis:

networks:
  external:
  internal:

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres@db/postgres
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY_BASE=asdfasdfasdf
      - HONEYBADGER_API_KEY=asdfasdfasdf
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
    ports:
      - 8081:80
      - 8443:443
    networks:
      - internal
      - external
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    networks:
      - internal
